name: Publish test coverage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Execute and generate the test coverage
        run: npm test

      - name: Publish coverage to codecov platform
        uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true
